# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('room', models.CharField(choices=[('dos', 'Sala 2'), ('principal', 'Sala Principal (con traducción)'), ('chica', 'Sala Chica'), ('talleres', 'Sala Talleres')], max_length=20)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'ordering': ['date', 'start', 'end'],
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.TimeSlot'),
        ),
    ]
