# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='talk',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text='True for lunch, break time, etc.'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='room',
            field=models.CharField(blank=True, choices=[('', '-----------'), ('dos', 'Sala 2'), ('principal', 'Sala Principal (con traducción)'), ('chica', 'Sala Chica'), ('talleres', 'Sala Talleres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Speaker'),
        ),
    ]
