version: '2'
services:
    back:
        image: workshopstarsconf_back
        volumes:
            - ./back:/src
        ports:
            - 8000:8000
    front:
        image: workshopstarsconf_front
        environment:
            - BACKEND_URL=http://localhost:8000
        volumes:
            - ./front:/src
        ports:
            - 8080:8080

