version: '2'
services:
    back:
        build: back
        volumes:
            - ./back:/src
        ports:
            - 8000:8000
    front:
        build: front
        environment:
            - BACKEND_URL=http://localhost:8000
        volumes:
            - ./front:/src
        ports:
            - 8080:8080

