#  /**
#  * @requires P03 - Agrega la categoria a cada Charla
#  */
query allSpeakersQuery {
  allTalks {
    id
    name
    speaker {
      name
    }
    timeSlot {
      id
      date
      start
      end
    }
    # category
    room
    isPlaceholder
  }
}
