# P05 Consulta a graphql, revisar localhost:8000/graphql
query allSpeakersQuery {
  allTalks {
    id
    name
    speaker {
      name
    }
    timeSlot {
      id
      date
      start
      end
    }
    room
    isPlaceholder
  }
}
